web:
  image:  vkiet/nginx
  ports:
    - "8888:80"
  volumes:
    #- ~/Projects/docker.magento/code:/code
    - ~/Projects/vee:/code
    - ~/Projects/docker.magento/nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
    - ~/Projects/docker.magento/nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - php

php:
  image: vkiet/php
  volumes:
    #- ~/Projects/docker.magento/code:/code
    - ~/Projects/vee:/code
    - ~/Projects/docker.magento/php/php.ini:/usr/local/etc/php/php.ini
  links:
    - db

db:
  image: mysql:5.7
  volumes:
    - ~/Docker_Data/mysql5.7:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: magento
    MYSQL_DATABASE: magento
    MYSQL_USER: magento
    MYSQL_PASSWORD: magento
