web:
  image:  kp/nginx:2
  ports:
    - "8008:80"
  volumes:
   # - ~/projects/magento/conf/compose/code:/code
    - ~/projects/magento/source:/code
    - ~/projects/magento/conf/compose/nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
    - ~/projects/magento/conf/compose/nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - php

php:
  image: kp/php:2
  volumes:
   # - ~/projects/magento/conf/compose/code:/code
    - ~/projects/magento/source:/code
    - ~/projects/magento/conf/compose/php:/usr/local/etc/php/
  links:
    - db

db:
  image: mysql:5.7
  volumes:
    - ~/projects/magento/database:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: magento
    MYSQL_DATABASE: magento
    MYSQL_USER: magento
    MYSQL_PASSWORD: magento